### ISSUE TITLE
Doc improvements

### ISSUE THREAD

**Issue by TonyGravagno** [SpicyWeb-de/nextcloud-user-ispconfig#4]
Please see: ISPConfig [forum post](https://www.howtoforge.com/community/threads/collaborate-to-update-nextcloud-ispconfig-howto.85935/): "Collaborate to update Nextcloud + ISPConfig HowTo?"

Would you like to exchange notes that lead to more detailed docs here and elsewhere?

**Comment by qroac** [comment]
If I understand your forum post correctly, you mention that this authentication app requires an ISPConfig api token. 
And because the ISPConfig API is not scoped on client level but gives access on the global level, you cannot use this app on Nextcloud installations where customers can access the config file.  
Please correct me, if I'm wrong.

This app has been developed to offer managed cloud services to some of our customers (listed in configured domains). For this scenario on ISP level, the usage of the global API is no problem. But I absolutely see your case. We had some customers that wanted to start their own cloud with the same authentication comfort. For that I hope that ISPConfig will some day have scoped API users. Than it shouldn't be a problem to offer this authentication method to customers as well ...  

What else information is missing in the readme file of this project?
